// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSlyPcgi4jNx55I4ayHZ21wZUhcXs5fQw',
    appId: '1:186960173803:android:31b299e2b9b9b16828bcae',
    messagingSenderId: '186960173803',
    projectId: 'kt78-dcd58',
    databaseURL: 'https://kt78-dcd58-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kt78-dcd58.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaffcl4pkrJFbWHIIN3DMFIzBk1oIX6FU',
    appId: '1:186960173803:ios:de5d0bdd5692753c28bcae',
    messagingSenderId: '186960173803',
    projectId: 'kt78-dcd58',
    databaseURL: 'https://kt78-dcd58-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kt78-dcd58.firebasestorage.app',
    iosClientId: '186960173803-2mkfgpv0pro5qq1ccs6v7u51ip1n4tlt.apps.googleusercontent.com',
    iosBundleId: 'com.idnkt78.semesta',
  );
}
